= Chapter 8 Questions
Kyle Aure <KAure09@winona.edu>
v1.0, 2019-03-26
:RepoURL: https://github.com/KyleAure/WSURochester
:AuthorURL: https://github.com/KyleAure
:DirURL: {RepoURL}/CS405

== Course Details
* **Course** - CS405
* **Instructor** - Dr. Dennis Martin

== Problem Set
Problem 9::
Question::::
Explain the difference between internal and external fragmentation.
Answer::::
Internal fragmentation is unused-allocated space, whereas external fragmentation is unused-unallocated space.
Problem 11::
Question::::
1. Memory partitions: M1=300 M2=600 M3=350 M4=200 M5=750 M6=125
2. Process sizes: P1=115 P2=500 P3=358 P4=200 P5=375
3. How would the first-fit, best-fit, and worst-fit algorithms place processes?
4. Rank the algorithms in terms of how efficiently they use memory.
Answer::::
*Bold* indicates the memory partition the process will occupy.
The memory cell will then be updated with remaining space available.
From the results below I would say that the Best-Fit solution works best.
Even though you need to search the entire list which may take time,
it resulted in the smallest holes while still having large memory partitions for new processes.
While, the Worst-Fit solution failed to have space left over for process 5.

.First-Fit
|===
|Process |M1=300 |M2=600 |M3=350 |M4=200 |M5=750 |M6=125
|P1=115 |M1=*300* |M2=600 |M3=350 |M4=200 |M5=750 |M6=125
|P2=500 |M1=185 |M2=*600* |M3=350 |M4=200 |M5=750 |M6=125
|P3=358 |M1=185 |M2=100 |M3=350 |M4=200 |M5=*750* |M6=125
|P4=200 |M1=185 |M2=100 |M3=*350* |M4=200 |M5=392 |M6=125
|P5=375 |M1=185 |M2=100 |M3=150 |M4=200 |M5=*392* |M6=125
|Result |M1=185 |M2=100 |M3=150 |M4=200 |M5=17 |M6=125
|===
.Best-Fit
|===
|Process |M1=300 |M2=600 |M3=350 |M4=200 |M5=750 |M6=125
|P1=115 |M1=300 |M2=600 |M3=350 |M4=200 |M5=750 |M6=*125*
|P2=500 |M1=300 |M2=*600* |M3=350 |M4=200 |M5=750 |M6=10
|P3=358 |M1=300 |M2=100 |M3=350 |M4=200 |M5=*750* |M6=10
|P4=200 |M1=300 |M2=100 |M3=350 |M4=*200* |M5=392 |M6=10
|P5=375 |M1=300 |M2=100 |M3=350 |M4=0 |M5=*392* |M6=10
|Result |M1=300 |M2=100 |M3=350 |M4=0 |M5=17 |M6=10
|===
.Worst-Fit
|===
|Process |M1=300 |M2=600 |M3=350 |M4=200 |M5=750 |M6=125
|P1=115 |M1=300 |M2=600 |M3=350 |M4=200 |M5=*750* |M6=125
|P2=500 |M1=300 |M2=600 |M3=350 |M4=200 |M5=*635* |M6=125
|P3=358 |M1=300 |M2=*600* |M3=350 |M4=200 |M5=135 |M6=125
|P4=200 |M1=*300* |M2=242 |M3=350 |M4=200 |M5=135 |M6=125
|P5=375 |M1=100 |M2=242 |M3=350 |M4=200 |M5=135 |M6=125
|===
Problem 25::
Question::::
1. Consider a paging system with the page table stored in memory.
2. If a memory reference takes 50 nanoseconds, how long does a paged memory reference take?
3. If we add TLBs, and 75 percent of all page-table references are found in the TLBs, what is the effective memory reference time? (Assume that finding a page-table entry in the TLBs takes 2 nanoseconds, if the entry is present.)
Answer:::
1. Paged memory reference will take 100ns, 50ns will be used to access the page table and 50ns will be used to access the data in memory.
2. In this case, there is a 75% chance that memory reference takes 50ns, the other 25% of time memory reference will take the full 100ns. Finally, we need to account for TLB lookup which will add 2ns whether or not the page is found. Therefore, (.75*50)+(.25*100)+2 = 64.5ns
