= Chapter 8 Questions
Kyle Aure <KAure09@winona.edu>
v1.0, 2019-03-26
:RepoURL: https://github.com/KyleAure/WSURochester
:AuthorURL: https://github.com/KyleAure
:DirURL: {RepoURL}/CS405

== Course Details
* **Course** - CS405
* **Instructor** - Dr. Dennis Martin

== Problem Set
Problem 9::
	Question::::
		Explain the difference between internal and external fragmentation.
	Answer::::
		Internal fragmentation is unused-allocated space, whereas external fragmentation is unused-unallocated space.
Problem 11::
	Question::::
		1. Given six memory partitions of 300 KB , 600 KB , 350 KB , 200 KB , 750 KB , and 125 KB (in order).
		2. Process sizes: 115 KB , 500 KB , 358 KB , 200 KB , and 375 KB (in order)
		3. How would the first-fit, best-fit, and worst-fit algorithms place processes?
		4. *Rank* the algorithms in terms of how efficiently they use memory.
	Answer::::
		1. M1=300KB, M2=600KB, M3=350KB, M4=200KB, M5=750KB, M6=125KB
		2. P1=115KB, P2=500KB, P3=358KB, P4=200KB, P5=375KB
		3. First-Fit
			.. P1=115 M1=*300* M2=600 M3=350 M4=200 M5=750 M6=125
			.. P2=500 M1=185 M2=*600* M3=350 M4=200 M5=750 M6=125
			.. P3=358 M1=185 M2=100 M3=350 M4=200 M5=*750* M6=125
			.. P4=200 M1=185 M2=100 M3=*350* M4=200 M5=392 M6=125
			.. P5=375 M1=185 M2=100 M3=150 M4=200 M5=*392* M6=125
		4. Best-Fit
			.. P1=115 M1=300 M2=600 M3=350 M4=200 M5=750 M6=*125*
			.. P2=500 M1=300 M2=*600* M3=350 M4=200 M5=750 M6=10
			.. P3=358 M1=300 M2=100 M3=350 M4=200 M5=*750* M6=10
			.. P4=200 M1=300 M2=100 M3=350 M4=*200* M5=392 M6=10
			.. P5=375 M1=300 M2=100 M3=350 M4=000 M5=*392* M6=10
		5. Worst-Fit
			.. P1=115
			.. P2=500
			.. P3=358
			.. P4=200
			.. P5=375
Problem 25::
	Question::::
		1. Consider a paging system with the page table stored in memory.
		2. If a memory reference takes 50 nanoseconds, how long does a paged memory reference take?
		3. If we add TLB s, and 75 percent of all page-table references are found in the TLB s, what is the effective memory reference time? (Assume that finding a page-table entry in the TLB s takes 2 nanoseconds, if the entry is present.)
	Answer:::
		1. Paged memory reference will take 100ns, 50ns will be used to access the page table and 50ns will be used to access the word in memory.
		2. In this case, there is a 75% chance that memory reference takes 50ns, the other 25% of time memory reference will take the full 100ns. Finally, we need to account for TLB lookup which will add 2ns wheather or not the page is found. Therfore, (.75*50)+(.25*100)+2 = 64.5ns
