= Chapter 12 Questions
Kyle Aure <KAure09@winona.edu>
v1.0, 2019-04-17
:RepoURL: https://github.com/KyleAure/WSURochester
:AuthorURL: https://github.com/KyleAure
:DirURL: {RepoURL}/CS405

== Course Details
* **Course** - CS405
* **Instructor** - Dr. Dennis Martin

== Problem Set
Problem 1::
Question::::
* Consider a file currently consisting of 100 blocks.
* Assume that the file control block (and the index block, in the case of indexed allocation) is already in memory.
* Calculate how many disk I/O operations are required for contiguous, linked, and indexed (single-level) allocation strategies, if, for one block, the following conditions hold:
** In the contiguous-allocation case, assume that there is no room to grow in the beginning, but there is room to grow in the end.
** Also, assume that the block information to be added is stored in memory.
** Assume there is a "tail" pointer to the last block in a linked file.
** Assume that when delete a block at beginning of contiguously allocated file, must move all subsequent blocks "down," so file starts with same block number.
a. The block is added at the beginning
b. The block is added in the middle
c. The block is added at the end
d. The block is removed from the beginning
e. The block is removed from the middle
f. The block is removed from the end
Answer::::
|===
|Question 	|Contiguous 	|Linked 	|Indexed

|a 			|201			|1			|1
|b 			|101			|52			|1
|c 			|1				|3			|1
|d 			|198			|1			|0
|e 			|98				|52			|0
|f 			|0				|100		|0
|===
Problem 10::
Question::::
Contrast the performance of the three techniques for allocating disk blocks (contiguous, linked, and indexed) for both sequential and random file access
Answer::::
* For *Sequential* allocation of disk blocks the contiguous and indexed tecniques are both going to perform similarly, but contiguous will have less space overhead.  Linked, however, does have a bit more performance overhead for sequential allocation since it needs to keep track of it's tail pointer.
* For *Random File Access* Indexed will be the best since allocating will take a constant amount of time.  The next best will be linked as at most it will need to do N/2 I/O operations.  Lastly, contiguous will be the worst performer as at most it will need to do N+1 I/O operations.
