= CS385 Lab 7
Kyle Aure <KAure09@winona.edu>
v1.0, 2018-11-15
:RepoURL: https://github.com/KyleAure/WSURochester
:AuthorURL: https://github.com/KyleAure
:DirURL: {RepoURL}/CS385

.Project Description
****
Using the Cup Database Schema develop sample queries.
Then normalize the Student Database used in the first few labs to first, second, and third normal forms.
Finally, identify update anomalies and functional dependencies in a car rental table.
****

== Course Details
* **Course** - CS385: Applied Database Management
* **Instructor** - Dr. Nicole Anderson

== Running project
No database files are needed for this project.  Sample data is provided below.

== Problem 1
=== Polling schema
* Color([underline]#colorID#, cupColor)
* Store([underline]#storeNum#, stateAbrv)
* State([underline]#stateAbrv#, stateName, numElectorialVotes)
* Receipt([underline]#receiptID#, storeNum, date)
* Cup([underline]#receiptID#, [underline]#colorID#)


=== Queries
1. Which cup had the largest sales in each state?
** Data Needed:
+
----

----
+
2. What is the distribution of cup sales in each state?
**
+
----
----
+
3. Who is currently predicted to win according to the 7-11 poll?
** 
+
----
----


== Problem 2
Normalize student database.
Original Schema:
- Student(fName, lName, favColor, pets, hometown, favMovies, shoeSize)

=== First NF

Goals: Define primary key, and remove multivalued attributes.

First NF Schema:

- Student([underline]#studentID#, fName, lName, homeCity, homeState, shoeSize)
- StudentPet([underline]#studentID#, pet)
- StudentMovie([underline]#studentID#, favMovie)

=== Second NF

Goals: Ensure attributes rely on the whole of the candidate key

Functional Dependencies:

- Student::studentID + ZipCode -> fName, lName, shoeSize, homeCity, homeState
- StudentPet::studentID -> pet
- StudentMovie::studentID - > favMovie

Second NF Schema:

- Student([underline]#studentID#, [underline]#zipCode#, fName, lName, shoeSize, homeCity, homeState)
- StudentPet([underline]#studentID#, pet)
- StudentMovie([underline]#studentID#, favMovie)

=== Third NF

Goals: Ensure attributes rely on nothing but the primary key

Functional Dependencies:

- Student::studentID -> fName, lName, shoeSize, zipCode
- Hometown::zipCode -> homeState, homeCity
- StudentPet::studentID -> pet
- StudentMovie::studentID - > favMovie

Third NF Schema:

- Student([underline]#studentID#, fName, lName, shoeSize, zipCode)
- Hometown([underline]#zipCode#, homeState, homeCity)
- StudentPet([underline]#studentID#, pet)
- StudentMovie([underline]#studentID#, favMovie)

== Problem 3

=== Anomalies
1. Insertion - If you get a new car there is no where to store the registration, make, and model without having a customer to rent the car.
2. Deletion - If a shop location closes, then all the car and customer data from that shop is also lost.
3. Modification - If a customer changes their last name then all records for that customer need to be changed as well.

=== Functional Dependencies
- carReg -> carMake, carModel
** This is assuming that no two cars even if they are from different states will have the same registration number.
- custNo -> custName
** This is assuming that if the same customer goes to different shops they are not given separate customer numbers.
- shopNo -> shopLoc
** No assumptions here this is just logical.
- receiptNo -> carReg, custNo, shopNo, rentalDate
** The last attribute that is not functionally dependent on the rest of the schema is rentalDate. This should be functionally dependent on something outside the current schema like a receipt.
