= Student Introduction
Kyle Aure <KAure09@winona.edu>
v1.0, 2019-01-16
:RepoURL: https://github.com/KyleAure/WSURochester
:AuthorURL: https://github.com/KyleAure
:DirURL: {RepoURL}/CS411

.Project Description
****
Introduction to be presented in next class.
****

== Biography
My name is Kyle Aure.
I am a working towards my second bachelor's degree in Computer Science.
My first bachelor's degree is in Secondary Math Education.
I currently work full-time in the Welcome Center for RCTC and WSU-Rochester.
I did an internship last summer at IBM as a backend software developer.

== Goals
My goals for this course is to get a better understanding of quality standards in the software development industry.
I also hope this course will allow me to obtain third-party certifications that will help my employability in the future.

== Plans for Future
I plan on working in backend software development for a while.
I intend to continue my education fairly soon after completing my bachelors degree.
I hope that in the future I will be able to teach undergraduate coursework in computer science.
