= Homework 1
Kyle Aure <KAure09@winona.edu>
v1.0, 2019-03-09
:RepoURL: https://github.com/KyleAure/WSURochester
:AuthorURL: https://github.com/KyleAure
:DirURL: {RepoURL}/CS435
:stem: asciimath

.Homework Description
****
Introduction assignment to languages, grammar, and finite state machines. 
****

== Course Details
* **Course** - CS435
* **Instructor** - Dr. Chi-Cheng Lin

== Homework Results

Question 1::
Let asciimath:[L_1 = {a^n b^n: n >= 0}]. Let asciimath:[L_2 = {c^n : n>0}]. For each of the following strings state whether or not it is an element of asciimath:[L_1 L_2].
Answer::
TODO
a. asciimath:[epsilon]
b. aabbcc
c. aabbcccc
d. aabcc

Question 2::
Let asciimath:[L_1 = {a^n b^n: n >= 0}]. Let asciimath:[L_2 = {c^n : n>0}]. For each of the following strings state whether or not it is an element of asciimath:[L_1 uu L_2].
Answer::
TODO
a. asciimath:[epsilon]
b. aabbcc
c. cccc
d. aabb

Question 3::
Let asciimath:[L = {w in {a,b}** : abs(w) -=_3 0}]. List the first six elements in the lexicographic enumeration of L. 
Answer::
TODO

Question 4::
asciimath:[L = {w in {a,b}** : x in {a,b}** (w=ax)}].
Answer::
TODO
a. Give a simple, precise English description for the language _L_.
b. List the first six element in the lexicographic enumeration of _L_.

Question 5::

Answer::

Question 6::
- K - finite set of states
- asciimath:[Sigma] - is an alphabet
- asciimath:[s in K] - is the initial state
- asciimath:[A sube K] - is the set of accepting states
- asciimath:[delta] - is the transition function from asciimath:[(K x Sigma to K)]
Answer::