== Quiz 2 Solutions

17/19

1. The most important symmetric algorithms, all of which are block ciphers, are the DES, triple DES, and the __________.
** Advanced Encryption Standard (AES)
2. __________ is the scrambled message produced as output.
** Ciphertext
3. A message authentication code is a small block of data generated by a secret key and appended to a message
** True
4. On average, __________ of all possible keys must be tried in order to achieve success with a brute-force attack.
** Half
5. A _________ protects against an attack in which one party generates a message for another party to sign
** strong hash function
6. Symmetric encryption is used primarily to provide confidentiality
** True
7. Combined one byte at a time with the plaintext stream using the XOR operation, a __________ is the output of the pseudorandom bit generator.
** Keystream
8. The purpose of a __________ is to produce a “fingerprint” of a file, message, or other block of data.
** hash function
9. The purpose of the DSS algorithm is to enable two users to securely reach agreement about a shared secret that can be used as a secret key for subsequent symmetric encryption of messages.
** False
10. The strength of a hash function against brute-force attacks depends solely on the length of the hash code produced by the algorithm.
** True
11. __________ is a procedure that allows communicating parties to verify that received or stored messages are authentic.
** Message authentication
12. Transmitted data stored locally are referred to as __________.
** Data at rest
13. If the only form of attack that could be made on an encryption algorithm is brute-force, then the way to counter such attacks would be to __________ .
** use longer keys
14. __________ is a block cipher in which the plaintext and ciphertext are integers between 0 and n-1 for some n.
** RSA (Rivest, Shamir, Adleman)
15. The __________ is the encryption algorithm run in reverse
** decryption algorithm
16. A __________ is created by using a secure hash function to generate a hash value for a message and then encrypting the hash code with a private key.
** xx-secret key
17. Digital signatures and key management are the two most important applications of __________ encryption.
** xx-advance
18. A  __________ is to try every possible key on a piece of ciphertext until an intelligible translation into plaintext is obtained.
** brute-force attack
19. The original message or data that is fed into the algorithm is __________.
** plaintext
