= CS415 Chapter 2 Exercises
Kyle Aure <KAure09@winona.edu>
v1.0, 2018-09-10
:RepoURL: https://github.com/KyleAure/WSURochester
:AuthorURL: https://github.com/KyleAure
:DirURL: {RepoURL}/CS415

.Exercise Description
****
Complete from our book Chapter 2 assignments 2.1f, 2.12 and extra try 2.15a-c.
This can be handed in or uploaded.
Be sure to number your answers, and include your name and class number.
****

== Problems
=== 2.1f
P. Write a regular expression to capture the following:
D. Financial quantities in American notation.
1. Leading dollar sign ($),
2. An optional string of asterisks ,
3. A string of decimal digits,
4. An optional fractional part consisting of a decimal point (.) and two decimal digits.
5. The string of digits to the left of the decimal point may consist of a single zero (0).
6. Otherwise it must not start with a zero.
7. If there are more than three digits to the left of the decimal point, groups of three (counting from the right) must be separated by commas (,).

A.

=== 2.12

=== Extra Credit 2.15 a-c
