= Quiz 1 Solutions

1. A lexical error, detected by the scanner
** ‘@’ sign outside of a string or comment
2. A syntax error, detected by the parser
** Mismatched parentheses in an arithmetic expression
3. A static semantic error, detected by semantic analysis
** Use of an identifier that was never declared
4. A dynamic semantic error, detected by code generated by the compiler
** Divide by Zero
5. An error that the compiler can neither catch nor easily generate code to catch
** Failure to reclaim dynamically allocated objects that are no longer needed (“memory leak”)
6. What does NOT make a language successful?
** Expensive Proprietary IDE
7. Which of the following is an example of a declarative language?
** LISP
8. Which of the following is an example of an imperative language?
** Java
9. Which compiler produces nothing bug virtual instructions?
** Java Byte Code
10. Compilation:
** Entails semantic understanding of what is being processed
11. Avoid requiring something to be stated more than once; factor out the recurring pattern describes:
** Abstraction
12. "Confine your attention to designs that look good because they are good" describes:
** Elegance
13. "Avoid arbitrary sequences more than a few items long" describes
** Labeling
14. "Independent functions should be controlled by independent mechanisms." describes
** Orthogonality
15. "Do no ask users what they want; find out what they need" describes
** Responsible Design
16. "Avoid features or facilities that are dependent on a particular computer or a small class of computers" describes
** Portability
17. "The static structure of the program should correspond in a simple way to the dynamic structure of the corresponding computations" describes
** Structure
18. "No program that violates the definition of the language, or its own intended structure, should escape detection" describes
** Security
19. "Similar things should look similar, different things different" describes
** Syntactic Consistency
20. "The language should allow their representation of information that the user might know and that the compiler might need" describes
** Preservation of Information
