== Week 16 Quiz
Software Quality Assurance Chapters 23, 24, 25

Score: 10/10

1. ISO9000-3 standards include requirements in which of the following groups
** all of the above
2. IEEE standards can be applied to 3 classes.  Which of the following is not allocated to the conceptual standards class:
** IEEE 828
3. Which of the following is not included in the reasons to follow project process standards:
** Guarantees lower overall project cost
4. Project process standards are covered by:
** All of these
5. Which of the following is not a goal of quality management assessment standards:
** Allow the customer to select the most qualified supplier for their task
6. In order to obtain ISO 9000-3 certification, organizations must:
** all of these
7. IEEE standards can be applied to 3 classes.  Which of the following is not allocated to the prescriptive standards of conformance class:
** IEEE 1233
8. IEEE standards can be applied to 3 classes.  Which of the following is not allocated to the guidance standards class:
** IEEE 12207.3
9. Which of the following organizations does not contribute to SQA standards:
** NIH
10. Which is a benefit of using standards:
** All of the above
