= Quiz 1 Solutions

1/5

* A lexical error, detected by the scanner
** divide by zero
** *'@' sign outside of a string or comment*
** use of an identifier that was never declared
** mismatched parentheses in an arithmetic expression

* A syntax error, detected by the parser
** failure to reclaim dynamically allocated objects that are no longer needed (“memory leak”)
** '@' sign outside of a string or comment
** *use of an identifier that was never declared*
** mismatched parentheses in an arithmetic expression

* A static semantic error, detected by semantic analysis
** failure to reclaim dynamically allocated objects that are no longer needed (“memory leak”)
** '@' sign outside of a string or comment
** use of an identifier that was never declared
** *divide by zero*

* A dynamic semantic error, detected by code generated by the compiler
** *failure to reclaim dynamically allocated objects that are no longer needed (“memory leak”)*
** mismatched parentheses in an arithmetic expression
** use of an identifier that was never declared
** divide by zero

* An error that the compiler can neither catch nor easily generate code to catch
** *failure to reclaim dynamically allocated objects that are no longer needed (“memory leak”)*
** mismatched parentheses in an arithmetic expression
** use of an identifier that was never declared
** divide by zero

12345

* What does NOT make a language successful?

* Which of the following is an example of a declarative language?

* Which of the following is an example of an imperative language?

* Which compiler produces nothing bug virtual instructions?

* Compilation:

* Avoid requiring something to be stated more than once; factor out the recurring pattern describes:

* "Confine your attention to designs that look good because they are good" describes:

* "Avoid arbitrary sequences more than a few items long" describes

* "Independent functions should be controlled by independent mechanisms." describes

* "Do no ask users what they want; find out what they need" describes

* "Avoid features or facilities that are dependent on a particular computer or a small class of computers" describes

* "The static structure of the program should correspond in a simple way to the dynamic structure of the corresponding computations" describes

* "No program that violates the definition of the language, or its own intended structure, should escape detection" describes

* "Similar things should look similar, different things different" describes

* "The language should allow their representation of information that the user might know and that the compiler might need" describes
